### ISSUE TITLE
LightProbes not changing

### ISSUE THREAD

**Issue by MephestoKhaan** [laurenth-unity/lightmap-switching-tool#9]
First of all: thanks, this is a great tool :)

Scond: I added the same lightprobe group to the Light and Dark scenes (without geometry) and disabled it in the geometry scene. For some reason my lightprobes are always black but the lightmaps are changing fine.

**Comment by laurenth-unity** [comment]
I believe this is due to the tetrahedralization of the lightprobes which must be stored in the lighting data asset. The connections between the lightprobes are stored in the lighting data asset and if the lighting data asset that gets loaded doesn't contain these connections they cannot be created at runtime.

**Comment by MephestoKhaan** [comment]
What should I do then? Use just light probes in the main scene? (does not seem to work either) I have tried so many combinations I am a bit lost now haha

**Comment by laurenth-unity** [comment]
what platform and what unity version are you on ?

**Comment by MephestoKhaan** [comment]
Android 560f3

**Comment by laurenth-unity** [comment]
Oh, good to read :) This play / stop step is very annoying... but hopefully I can improve it in the future.
